### ISSUE TITLE
Log-analysis stack upgrades broken

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#1895]
### Describe the bug

#1878 changed a custom resource type - CloudFormation will fail hard and refuse to update existing stacks:

```
16:14:15	ERROR	[deploy]	    X panther-log-analysis failed (5/9): stack panther-log-analysis change set is FAILED: Update of resource type is not permitted. The new template modifies resource type of the following resources: [UpdateGlueTables]
```

### Steps to reproduce

1. Deploy before #1878
1. Deploy current `master`
1. See error message

### Expected behavior

`mage deploy` always works on top of stacks from the last version

**Comment by rleighton** [comment]
Fixed https://github.com/panther-labs/panther/pull/1891

**Comment by austinbyers** [comment]
It is not fixed. The custom type is still incorrect in master: https://github.com/panther-labs/panther/blob/master/deployments/log_analysis.yml#L131
